### PR TITLE
Reveal back

### PR DESCRIPTION
**Pull request by efatsi**
The most interesting work here is the new logic in `RevealBackCard` (and Color), with some convoluted logic in the `forbidden_by` method, and which leans on two analog actions for resolution purposes:
- a `RevealCard` analog to show the other user their card
- a `CardShare` analog to resolve conditional effects that are tied to card sharing

Example: Psych + Shy
reveal_back_shy

Example: the ol "hey how about you show me your color first and i'll show you mine after but surprise i'm a hot potato" trick
reveal_back_potato

### CODE REVIEW

**Review by colorlace — COMMENTED** [review]
This comment is based on the hot potato gif. The hot potato should probably  not transfer hands after a "share back". Might be a pain since it resolves as a color share, but you should agree to a share beforehand to swap with the hot potato

**Comment by efatsi** [comment]
Hmmm, I think I disagree. I think the important part of someone "agreeing" to a card share is: their willingness to reveal their own card. So if they've revealed their card already, I think we can use that fact to assume that they agreed to a card share.

**Comment by colorlace** [comment]
The Rules say otherwise:

> From character guide: "the HOT POTATO power: any player that card shares or color shares with you immediately trades cards with you."
> 
> From rulebook: "SHARE - 2 players consenting to showing one another the same information about their own character cards."

The way it's coded up now gives the Hot Potato a slight edge on getting rid of it (could feign shyness?). May not matter much, or may be one of those game balancing things with unforeseen consequences.

**Comment by efatsi** [comment]
## Argument that we're not bending to rules too much here

> SHARE - 2 players consenting to showing one another the same information about their own character cards

i feel like the following statements are roughly equivalent:
- 2 players consent to reveal their cards to each other
- 1 person consents to reveal their card to someone, and the recipient consents to reveal their card back

## Argument for keeping it even if we are bending the rules

Imagine that we remove this `Reveal + RevealBack => Share` functionality. Then imagine you're the hot potato and someone reveals their card to you. If you're trying to potato them, you would then have to request a card-share. Which would probably be suspicious since the only reason you would need to share instead of reveal back would be to kick off some share-specific effect (which probably isn't good for the other player).

I think allowing people to reveal to & from each other while bypassing share effects would open a loophole in the game, and people could just avoid using the share functionality if there was a hot potato swimming around.

**Pull request merged**
